### ISSUE TITLE
netmask in vagrant file

### ISSUE THREAD

**Issue by zxwind** [vfarcic/ms-lifecycle#12]
Hi,

I think netmask needs to be set in vagrant file as some of the VMs not in the default subnet (255.255.255.0).

With the default settings, cd VM can't connect to serv-disc- VMs. Add subnet 255.255.0.0 fixes this for me.

**Comment by vfarcic** [comment]
Vagratfile, as it is now, works well in most combinations. I tested it on my laptops with OS X, Windows, and Ubuntu. That does not mean that it'll work with all hosts configs.

I'm glad that you managed to fix it and that it now works in your host.
