### ISSUE TITLE
Elasticsearch container does not start due to limited memory

### ISSUE THREAD

**Issue by gchinis** [vfarcic/ms-lifecycle#13]
The docker log:

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000085330000, 2060255232, 0) failed; error='Cannot
allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2060255232 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log


```

I had to get the VM memory up to 6GB to make it work.

**Comment by gchinis** [comment]
It seems to be related to https://github.com/docker-library/elasticsearch/issues/98

**Comment by vfarcic** [comment]
The problem is related to the latest release 5 of the ELK stack. I changed Ansible roles to use versions 2 (EL) and 4 (K) until this is fixed.

Pull the latest code from the vfarcic/ms-lifecycle repo and try it out.

Please reopen the ticket if you notice any problem.
