### ISSUE TITLE
Bare variables aren't supported anymore (ansible 2.0+)

### ISSUE THREAD

**Issue by dgorniak** [vfarcic/ms-lifecycle#14]
## Replication

After starting with fresh ms-lifecycle  docker box I've ended up with an error:

`$ vagrant up cd --provision`
`...`
`==> cd: fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'host_ip'\n\nThe error appears to have been in '/vagrant/ansible/roles/common/tasks/main.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Host is present\n  ^ here\n"}
`

## Fix

According to ansible 2.0 [changelog](https://raw.githubusercontent.com/ansible/ansible/stable-2.0/CHANGELOG.md) bare variables aren't supported anymore, they must use the full jinja2 syntax ('{{var_name}}').

ansible/roles/common/tasks/main.yml line 12: 

`   with_items: "{{ hosts }} "`

ansible/roles/common/tasks/main.yml line 20:  

`    with_items: "{{ obsolete_services }}"`

**Comment by msegoviadev** [comment]
This really helped ! Just to correct the typo, `with_items: "{{ obsolete_services }}"` is at ansible/roles/common/tasks/main.yml line 20
