### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by bweston92** [vfarcic/ms-lifecycle#2]
Say I'm using DigitalOcean and they assign me a private IP address, how would I rebuild the play books and hosts file to know what IP addresses need to be?

I seen DO just released tagging so maybe a little script to pull the boxes down and make the hosts file out of the tags?

**Comment by vfarcic** [comment]
Solved through a discussion in https://disqus.com/home/channel/thedevops20toolkit/discussion/channel-thedevops20toolkit/taking_it_to_the_cloud/
