### ISSUE TITLE
ERROR: for db  unknown log opt 'syslog-tag' for syslog log driver

### ISSUE THREAD

**Issue by timdau** [vfarcic/ms-lifecycle#20]
vagrant@prod:~/books-ms$ docker --version
Docker version 1.12.3, build 6b644ec

vagrant@prod:~/books-ms$ docker-compose --version
docker-compose version 1.7.1, build 0a9ab35

 vagrant@prod:~/books-ms$ docker-compose -p books-ms -f docker-compose-logging.yml up -d app

Status: Downloaded newer image for 10.100.198.200:5000/books-ms:latest
Creating booksms_db_1

ERROR: for db  unknown log opt 'syslog-tag' for syslog log driver
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1

May be related to this?
https://docs.docker.com/engine/deprecated/#/driver-specific-log-tags

**Comment by vfarcic** [comment]
You're right. Driver specific tags are deprecated. The code is updated. Please pull the latest books-ms code and let me know if you encounter any problem.

**Comment by timdau** [comment]
Maybe I have messed things up, but the filter that creates container_id isn't being run.

I can confirm that logstash is running with /conf/syslog.conf

**Comment by vfarcic** [comment]
I made a change quickly in order to avoid more people getting the error. I did not have time to truly test it yet. The problem is that I'm not sure I'll manage to spin up the whole environment and test before Friday. I hope that's not to late.

**Comment by timdau** [comment]
Please let me know what you come up with.

**Comment by vfarcic** [comment]
Sorry for not responding earlier. This was the first moment I could get 30 min. to explore the problem.

Actually, there is no problem at all. The things got a bit easier. Originally, the tag was sent to logstash as `docker/[TAG]` and stored as `program`. Not `docker/` disappeared so there is no need any more to transform `program` into `container_id`. The information you're looking for is now stored as `program`.
