### ISSUE TITLE
Deploying Containers to the production server (p91) vagrant provisioning broken

### ISSUE THREAD

**Issue by jhagege** [vfarcic/ms-lifecycle#23]
Hi,
When trying to provision the vagrant vm with vagrant up cd prod, I get the following error message:

```
TASK [docker : DockerUI is running] ********************************************
fatal: [10.100.198.201]: FAILED! => {"changed": false, "changes": ["{\"status\":\"Downloading from http://\"}\r\n", "{\"errorDetail\":{\"message\":\"Get http://: http: no Host in request URL\"},\"error\":\"Get http://: http: no Host in request URL\"}\r\n"], "failed": true, "msg": "Unrecognized status from pull.", "status": ""}
	to retry, use: --limit @/vagrant/ansible/prod.retry

PLAY RECAP *********************************************************************
10.100.198.201             : ok=10   changed=0    unreachable=0    failed=1 
```
Any idea what could cause that ?
Thanks

**Comment by jhagege** [comment]
Seems I'm outta luck, seems to be a very recent bug.
http://stackoverflow.com/questions/40895823/ansible-docker-container-no-host-in-request-url-docker-pull-works-correctly
Hope it gets fixed very soon..

**Comment by vfarcic** [comment]
Seems you're right.

They seem to be working on a fix. Let's wait for a while.

**Comment by vfarcic** [comment]
Related to https://github.com/docker/docker-py/issues/1321

**Comment by jhagege** [comment]
Seems to be working now after hotfix from Docker (they rollbacked to earlier version of requests package)

**Comment by vfarcic** [comment]
Thank you for debugging this problem and letting me know that now it works.
