### ISSUE TITLE
Vagrant Swarm nodes not available

### ISSUE THREAD

**Issue by jhagege** [vfarcic/ms-lifecycle#25]
Hi, for some reason while trying to run the command: `vagrant up cd swarm-master swarm-node-1 swarm-node-2`, I get this error:
```
The box 'ubuntu/wily64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:
```

Not sure why is this happening, but could another version work out fine ? 
Like Ubuntu 16.04/16.10 maybe ?
Thanks

**Comment by jhagege** [comment]
Updated to latest Vagrant version, and it fixed the issue.
Sorry for bothering :-)

**Comment by vfarcic** [comment]
No problem. Those things happen all the time.
