### ISSUE TITLE
Docker UI error

### ISSUE THREAD

**Issue by captainvim** [vfarcic/ms-lifecycle#27]
Viktor, thank you for writing the book. It is very informative. Under Implementation of the Deployment section, I ran vagrant up cd but I am getting an error on the Docker UI installation. 

Error message is as follows:

==> cd: TASK [docker : DockerUI is running] ********************************************
==> cd: fatal: [localhost]: FAILED! => {"changed": false, "error": "APIError(HTTPError(u'500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.21/images/create?tag=latest&fromImage=uifd%2Fui-for-docker',),)", "failed": true, "msg": "Failed to pull the specified image: uifd/ui-for-docker"}
==> cd:         to retry, use: --limit @/vagrant/ansible/cd.retry
==> cd:
==> cd: PLAY RECAP *********************************************************************
==> cd: localhost                  : ok=11   changed=10   unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

###########################################################################

I checked Docker Hub for the image, it looks like Docker-UI is already deprecated to Portainer.

**Comment by captainvim** [comment]
I will try to replace the Docker-UI with portainer to see if it will work or not.

**Comment by captainvim** [comment]
I tried portainer/portainer image but I got a similar error message. It looks like the issue is the docker syntax in Ansible playbook. 

http://docs.ansible.com/ansible/docker_module.html

**Comment by vfarcic** [comment]
Can you tell me which chapter you're reading so that I reproduce the problem on my laptop?

**Comment by captainvim** [comment]
Chapter: Implementation of the Deployment Pipeline: Initial Stages
I am using Windows 7 at work with VirtualBox 5.1.22 and Vagrant 1.8

**Comment by vfarcic** [comment]
@pitcha I just did a fresh install on my spare Windows laptop and it worked. Can you confirm that your laptop/network is not behind a firewall/VPB/proxy? If it isn't, can you enter the VM and re-run Ansible with verbose flag?

```bash
vagrant ssh cd

ansible-playbook /vagrant/ansible/cd.yml -c local -v
```

**Comment by captainvim** [comment]
Yes, I am behind a firewall/proxy. I already set the proxy code on Vagrantfile.

`  if Vagrant.has_plugin?("vagrant-proxyconf") `
`    config.proxy.http     = "http://myproxy"`
`    config.proxy.https    = "http://myproxy"`
`    config.proxy.no_proxy =  ""`
`  end`

Output of ansible-playbook with verbose command can be found in the URL below:

[https://s3-ap-southeast-1.amazonaws.com/pitcha/ansible_error_log.txt:](https://s3-ap-southeast-1.amazonaws.com/pitcha/ansible_error_log.txt)

**Comment by vfarcic** [comment]
You'll need to setup proxy in Docker config, apt, and change npm inside test container to use the proxy as well. It's tends to be tedious. Do you have an option to not use firewall/proxy?

**Comment by captainvim** [comment]
Thank you for your feedback/response. I've  configured the proxy for the components mentioned above but without success. I am exploring another option to use without proxy/firewall.
