### ISSUE TITLE
Timeout on the docker-compose 

### ISSUE THREAD

**Issue by rogerscuall** [vfarcic/ms-lifecycle#30]
I have noticed that in the pre-deployment test and post-deployment test the is a play that uses docker-compose and I'm getting almost always a timeout, just following the exactly the error and increasing the `COMPOSE_HTTP_TIMEOUT` to 300 fixes the problem and permits the playbook from stopping with errors.

**Comment by vfarcic** [comment]
I haven't faced the same issue nor heard of a similar from other readers. Is there a proxy or VPN that might cause such a delay?

**Comment by rogerscuall** [comment]
Nope, there is no VPN or proxy involved.

**Comment by vfarcic** [comment]
I added `.env` file with `COMPOSE_HTTP_TIMEOUT=300` to the `vfarcic/books-ms` repo. That should add that env. var. to all compose commands. Can you pull the latest code from the repo and give it a try?

**Comment by vfarcic** [comment]
Assuming that the issue is closed. Please reopen it if you're still experiencing the problem.

**Comment by rogerscuall** [comment]
Sorry I forgot to reply. That worked perfectly.
