### ISSUE TITLE
fatal: [10.100.198.201]: FAILED! => {"changed": false, "msg": "This module has been removed.  The module documentation may contain hints for porting"}

### ISSUE THREAD

**Issue by youssefhatem90** [vfarcic/ms-lifecycle#33]
Hi ,
I am following the amazing book "DevOps ToolKIt "
on page 204 after I ran the 2 VMs
# vagrant up cd prod
then I tried to run the first playbook
# ansible-playbook /vagrant/ansible/prod2.yml \ -i /vagrant/ansible/hosts/prod
but I got the below error 

TASK [registrator : Container is running] *****************************************************************************************************
fatal: [10.100.198.201]: FAILED! => {"changed": false, "msg": "This module has been removed.  The module documentation may contain hints for porting"}

That is the whole output

vagrant@cd:~$ ansible-playbook /vagrant/ansible/prod2.yml \
> -i /vagrant/ansible/hosts/prod
 [WARNING]: Found variable using reserved name: hosts

PLAY [prod] ***********************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************
ok: [10.100.198.201]

TASK [common : JQ is present] *****************************************************************************************************************
ok: [10.100.198.201]

TASK [common : Host is present] ***************************************************************************************************************
ok: [10.100.198.201] => (item={u'host_ip': u'10.100.198.200', u'host_name': u'cd'})
ok: [10.100.198.201] => (item={u'host_ip': u'10.100.198.201', u'host_name': u'prod'})
ok: [10.100.198.201] => (item={u'host_ip': u'10.100.198.202', u'host_name': u'logging'})
ok: [10.100.198.201] => (item={u'host_ip': u'10.100.194.201', u'host_name': u'serv-disc-01'})
ok: [10.100.198.201] => (item={u'host_ip': u'10.100.194.202', u'host_name': u'serv-disc-02'})
ok: [10.100.198.201] => (item={u'host_ip': u'10.100.194.203', u'host_name': u'serv-disc-03'})
ok: [10.100.198.201] => (item={u'host_ip': u'10.100.193.200', u'host_name': u'proxy'})
ok: [10.100.198.201] => (item={u'host_ip': u'10.100.192.200', u'host_name': u'swarm-master'})
ok: [10.100.198.201] => (item={u'host_ip': u'10.100.192.201', u'host_name': u'swarm-node-1'})
ok: [10.100.198.201] => (item={u'host_ip': u'10.100.192.202', u'host_name': u'swarm-node-2'})

TASK [common : Services are not running] ******************************************************************************************************
ok: [10.100.198.201] => (item=puppet)
ok: [10.100.198.201] => (item=chef-client)

TASK [docker : Debian add Docker repository and update apt cache] *****************************************************************************
ok: [10.100.198.201]

TASK [docker : Debian Docker is present] ******************************************************************************************************
ok: [10.100.198.201]

TASK [docker : Debian python-pip is present] **************************************************************************************************
ok: [10.100.198.201]

TASK [docker : Debian docker-py is present] ***************************************************************************************************
ok: [10.100.198.201]

TASK [docker : Debian files are present] ******************************************************************************************************
ok: [10.100.198.201]

TASK [docker : Debian Daemon is reloaded] *****************************************************************************************************
skipping: [10.100.198.201]

TASK [docker : vagrant user is added to the docker group] *************************************************************************************
ok: [10.100.198.201]

TASK [docker : Debian Docker service is restarted] ********************************************************************************************
skipping: [10.100.198.201]

TASK [docker : CentOS files are copied] *******************************************************************************************************
skipping: [10.100.198.201] => (item={u'dest': u'/etc/yum.repos.d/docker.repo', u'src': u'docker.centos.repo'}) 
skipping: [10.100.198.201] => (item={u'dest': u'/lib/systemd/system/docker.service', u'src': u'docker.centos.service'}) 

TASK [docker : CentOS package is installed] ***************************************************************************************************
skipping: [10.100.198.201]

TASK [docker : CentOS Daemon is reloaded] *****************************************************************************************************
skipping: [10.100.198.201]

TASK [docker : CentOS service is running] *****************************************************************************************************
skipping: [10.100.198.201]

TASK [docker-compose : Executable is present] *************************************************************************************************
ok: [10.100.198.201]

TASK [consul : Directories are created] *******************************************************************************************************
ok: [10.100.198.201] => (item=/data/consul/data)
ok: [10.100.198.201] => (item=/data/consul/config)
ok: [10.100.198.201] => (item=/data/consul/logs)

TASK [consul : Files are copied] **************************************************************************************************************
ok: [10.100.198.201] => (item={u'dest': u'/usr/local/bin/consul', u'src': u'consul', u'mode': u'0755'})

TASK [consul : Is running] ********************************************************************************************************************
changed: [10.100.198.201]

TASK [consul : Has joined] ********************************************************************************************************************
skipping: [10.100.198.201]

TASK [registrator : Container is running] *****************************************************************************************************
fatal: [10.100.198.201]: FAILED! => {"changed": false, "msg": "This module has been removed.  The module documentation may contain hints for porting"}
	to retry, use: --limit @/vagrant/ansible/prod2.retry

PLAY RECAP ************************************************************************************************************************************
10.100.198.201             : ok=14   changed=1    unreachable=0    failed=1   

also when I tried the next playbook 
# ansible-playbook /vagrant/ansible/jenkins-node.yml > -i /vagrant/ansible/hosts/prod  >> it is ok
then
# ansible-playbook /vagrant/ansible/jenkins.yml -c local
I got a similar error

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ******************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************
ok: [localhost]

TASK [consul-template : Directory is created] *************************************************************************************************
ok: [localhost]

TASK [consul-template : File is copied] *******************************************************************************************************
ok: [localhost]

TASK [consul-template : Example template is copied] *******************************************************************************************
ok: [localhost] => (item=example.ctmpl)
ok: [localhost] => (item=example2.ctmpl)

TASK [jenkins : Directories are created] ******************************************************************************************************
ok: [localhost] => (item={u'src': u'credentials.xml', u'file': u'credentials.xml', u'dir': u'/data/jenkins', u'mode': u'0777'})
ok: [localhost] => (item={u'src': u'cd-config.xml', u'file': u'config.xml', u'dir': u'/data/jenkins/nodes/cd', u'mode': u'0777'})
ok: [localhost] => (item={u'src': u'prod-config.xml', u'file': u'config.xml', u'dir': u'/data/jenkins/nodes/prod', u'mode': u'0777'})
ok: [localhost] => (item={u'src': u'swarm-master-config.xml', u'file': u'config.xml', u'dir': u'/data/jenkins/nodes/swarm-master', u'mode': u'0777'})
ok: [localhost] => (item={u'src': u'LogParserPublisher.xml', u'file': u'hudson.plugins.logparser.LogParserPublisher.xml', u'dir': u'/data/jenkins', u'mode': u'0777'})
ok: [localhost] => (item={u'src': u'parsing_rules', u'file': u'parsing_rules', u'dir': u'/data/jenkins', u'mode': u'0777'})
ok: [localhost] => (item={u'src': u'scriptApproval.xml', u'file': u'scriptApproval.xml', u'dir': u'/data/jenkins', u'mode': u'0644'})

TASK [jenkins : Container is running] *********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "This module has been removed.  The module documentation may contain hints for porting"}
	to retry, use: --limit @/vagrant/ansible/jenkins.retry

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1

**Comment by vfarcic** [comment]
Ansible changed the syntax for `docker` module. Now it is split into multiple modules and the one that runs containers is now `docker_container`.

The repo is updated. Can you please pull the latest version and let me know if it works as expected?

**Comment by youssefhatem90** [comment]
I think we need another modification as I got the below error

TASK [jenkins : Container is running] *********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error: docker-py version is 1.6.0. Minimum version required is 1.7.0."}
	to retry, use: --limit @/vagrant/ansible/jenkins.retry

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1

**Comment by vfarcic** [comment]
Can you please confirm that you pulled the latest code? I changed `docker-py` as well in the last commit. You can see it in https://github.com/vfarcic/ms-lifecycle/commit/7540afd30e162863d1fd90cf4c275d5a09a0bc90
