### ISSUE TITLE
HAProxy Ansible configuration error - docker_container module doesn't have cap_add

### ISSUE THREAD

**Issue by cgarbin** [vfarcic/ms-lifecycle#35]
When configuring the HAProxy with `ansible-playbook /vagrant/ansible/haproxy.yml -i /vagrant/ansible/hosts/proxy` I get the following error:

```
TASK [haproxy : Container is running] **********************************************************
fatal: [10.100.193.200]: FAILED! => {"changed": false, "msg": "Unsupported parameters for
 (docker_container) module: cap_add ...
```

I believe the error started after the deprecated Ansible `docker` module was replaced with the new `docker_container` module. The file `roles/haproxy/tasks/main.yml` still has `cap_add`. It looks like the new equivalent parameter in `docker_module` is `capabilities` ([reference](http://docs.ansible.com/ansible/latest/modules/docker_container_module.html#parameters)).

**Comment by vfarcic** [comment]
Can you please pull the latest ms-lifecycle code and try it again?

**Comment by cgarbin** [comment]
It worked fine this time. Thanks for the prompt reply.
