### ISSUE TITLE
Ansible task ensuring docker-flow executable is present fails when provisioning cd

### ISSUE THREAD

**Issue by jeromefroe** [vfarcic/ms-lifecycle#5]
Hi! I've been working my way through your book The Devops 2.0 Toolkit (really like it so far) and I recently ran into an error when trying to provision the `cd` server. Specifically, if I bring up the  server with: `vagrant up cd --provision` I get the following error:

```

TASK [docker-flow : Executable is present] *************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: type object got multiple values for keyword argument 'status'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1463952298.41-197191465069865/get_url\", line 3234, in <module>\n    main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1463952298.41-197191465069865/get_url\", line 313, in main\n    tmpsrc, info = url_get(module, url, dest, use_proxy, last_mod_time, force, timeout, headers)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1463952298.41-197191465069865/get_url\", line 186, in url_get\n    rsp, info = fetch_url(module, url, use_proxy=use_proxy, force=force, last_mod_time=last_mod_time, timeout=timeout, headers=headers)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1463952298.41-197191465069865/get_url\", line 3223, in fetch_url\n    info.update(dict(msg=str(e), status=e.code, **e.info()))\nTypeError: type object got multiple values for keyword argument 'status'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

I looked into the docker-flow role and found that it was using the `get_url` module to download `docker-flow` from the following URL: `https://github.com/vfarcic/docker-flow/releases/download/{{ docker_flow_version }}/docker-flow_linux_amd64`. The default value for `docker_flow_version` is `v1.0-beta`, so the URL becomes `https://github.com/vfarcic/docker-flow/releases/download/v1.0-beta/docker-flow_linux_amd64`, but when I tried to use wget to download docker-flow from this URL from the command line I got a 404 Not Found error. I then tried `v1.0` instead of `v1.0-beta` and was able to download it successfully. Furthermore, when I made this change in the `defaults` folder the playbook ran successfully as well. I just wanted to bring this to your attention since it appears there have been some changes to `docker-flow` recently and I wasn't sure if one of them may have broken this playbook as it currently is. Thanks!

**Comment by vfarcic** [comment]
Thank you for letting me know this. You're right. The correct version is v1.0. I just fixed the code.
