### ISSUE TITLE
Issue while provisioning the logging and monitoring stack

### ISSUE THREAD

**Issue by Rivsoft** [vfarcic/ms-lifecycle#9]
Hi Viktor:

I am currently having an issue while provisioning the ELK stack for the Monitoring and Logging chapter on your DevOps 2 book.

I have double checked the commands and they seem correct but after executing the mentioned ansible playbook I am getting the following error for the logstash container:

{:timestamp=>"2016-08-20T18:31:40.363000+0000", :message=>"No config files found: /conf/config.conf\nCan you make sure this path is a logstash config file?", :level=>:error}

I have checked and I do have the proper config.conf file in my /data/logstash/conf/file.conf so the only thing that I can think of is a change in the logstash image (maybe a config format change ?), file permissions or docker volume mounting issue. 

I am sorry to bother on this but I am really interested in this chapter and want to see how this stacks works.

Please let me know if you need something else.

Best regards and great book btw. It has been a blast.

**Comment by vfarcic** [comment]
I do not have internet access with me until Friday (writing this from my mobile). I'll get back to you on Monday.

**Comment by Rivsoft** [comment]
Disregard this issue. It was a typo on my end. Thanks for your quick response.
